#!name=去开屏广告
#!desc=去除一些app开屏广告
#!author=hank-yuan
#!url=https://raw.githubusercontent.com/hank-yuan/IOS-rules/master/QuantumultX/Rewrite/StartUpAdBlock.conf
#!icon=https://raw.githubusercontent.com/hank-yuan/IOS-rules/master/IconSet/Adblock.png

hostname = emdcadvertise.eastmoney.com, v.icbc.com.cn

# > 02 东方财富 emdcadvertise.eastmoney.com
^https?:\/\/emdcadvertise\.eastmoney\.com\/infoService\/v\d url reject

# > 01 工商银行
# hostname = v.icbc.com.cn
# 如开启可自行添加主机名
^https?:\/\/v\.icbc\.com\.cn\/userfiles\/Resources\/WAP\/advertisement\/ url reject-200
